### ISSUE TITLE
Negative value of meter#1

### ISSUE THREAD

**Issue by magpern** [erikarenhill/solaredge-modbus-hass#13]
Why is the value negative? How should it be interpreted?
No production is active. It is night time

![image](https://user-images.githubusercontent.com/6589760/83454035-d02fe380-a45b-11ea-821f-ad1bd0ae219f.png)

**Comment by pkret** [comment]
You have probably already figured this out by now, but it means that you are buying/pulling 2.6kW from the grid at that moment. If you are interested in the solar output, see sensor.solaredge_modbus, for how much you are selling to (or buying from) the grid use sensor.solaredge_modbus_meter_1. And difference between both is what your home is using at that moment.
```
        solaredge_usage_now:
            friendly_name: "Usage"
            value_template: "{{ states('sensor.solaredge_modbus')|int - states('sensor.solaredge_modbus_meter_1')|int }}"
            unit_of_measurement: 'W'
```

**Comment by magpern** [comment]
> You have probably already figured this out by now

Yes, thanks anyway. I jumped the gun a little too early.

**Comment by magpern** [comment]
Any idea of how to get this value as a positive value?

I have reconfigured my external meter to just be a consumption meter. So, for me the value should be positive, meaning "Consumption power usage" instead of "AC power output"

**Comment by pkret** [comment]
Create a new template sensor and add *-1... it will then be negative when exporting power to the grid:

```
sensor:
  - platform: template
    sensors:
        solaredge_meter_power_output:
          friendly_name: "Consumption power usage"
          value_template: "{{ state_attr('sensor.solaredge_modbus_meter_1', 'ac_power_output')|int * -1 }}"
          unit_of_measurement: 'W'
```
