### ISSUE TITLE
Feature request: support for energy module in 2021.8.0

### ISSUE THREAD

**Issue by membersound** [erikarenhill/solaredge-modbus-hass#34]
Is it possible to add the following sensor attributes for support the new energy integration that will come in HA version 2021.8.0?
https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes/

When I look for my solaredge sensors in the new 2021.8.0 energy monitoring, they are not listed and refers to:
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by theautomation** [comment]
+1

**Comment by erikarenhill** [comment]
Hi all, sorry for late reply but it's not a problem using this component with energy-dashboard either. Just add a utility meter:

```
utility_meter:
  solar_production_daily:
    source: sensor.solaredge_lifetime_production
    cycle: daily
```

I will look into adding the state_class to use the sensors directly
